<a href="https://colab.research.google.com/github/girisoura/pytorch-deeplearning/blob/main/pytorch_training_piprline_nnModule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [ ]:
#create dataset
features= torch.rand(10,5)

# create model
model = Model(features.shape[1])

#call model for forward pass
model(features)


tensor([[0.4264],
        [0.4426],
        [0.4352],
        [0.4280],
        [0.4400],
        [0.4469],
        [0.4428],
        [0.4406],
        [0.4552],
        [0.4439]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2901, -0.0366, -0.0363, -0.1372, -0.0118],
        [ 0.3646, -0.2806,  0.4324,  0.2262, -0.0925],
        [-0.3898, -0.4171, -0.2134, -0.2427, -0.0299]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Sequential Container**

In [ ]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
    nn.Linear(num_features,3),
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )
  def forward(self, features):
    out= self.network(features)
    return out

In [ ]:
#create dataset
features= torch.rand(10,5)

# create model
model = Model(features.shape[1])

#call model for forward pass
model(features)


tensor([[0.4046],
        [0.3906],
        [0.4084],
        [0.4045],
        [0.3759],
        [0.3727],
        [0.4072],
        [0.4407],
        [0.3901],
        [0.3680]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.network

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)

**pipeline**

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.85335041, -0.64074796, -0.88721185, ..., -1.15178209,
        -0.8341636 , -0.73655591],
       [-1.25561895, -0.29595315, -1.26244455, ..., -1.38380534,
         0.25936257, -0.30269283],
       [ 0.56091791,  0.31209716,  0.56546902, ...,  0.61934872,
         0.33399492, -0.12465557],
       ...,
       [ 0.20872658,  0.63825442,  0.19183137, ...,  0.20609488,
         0.43134146,  0.45108951],
       [-0.36908733, -1.22550133, -0.30980809, ...,  0.58628841,
        -0.41881835,  1.83649323],
       [ 1.12222285,  0.28181113,  1.11974473, ...,  0.50964861,
         0.28694409, -0.30926651]])

In [ ]:
y_train

428    B
467    B
328    M
410    B
401    B
      ..
393    M
78     M
413    B
247    B
516    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
loss_function= nn.BCELoss()

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6446288824081421
Epoch: 2, Loss: 0.5028384327888489
Epoch: 3, Loss: 0.42494601011276245
Epoch: 4, Loss: 0.3751802146434784
Epoch: 5, Loss: 0.3401220440864563
Epoch: 6, Loss: 0.31378474831581116
Epoch: 7, Loss: 0.2930879294872284
Epoch: 8, Loss: 0.27627572417259216
Epoch: 9, Loss: 0.26226910948753357
Epoch: 10, Loss: 0.2503657042980194
Epoch: 11, Loss: 0.24008676409721375
Epoch: 12, Loss: 0.23109383881092072
Epoch: 13, Loss: 0.22314010560512543
Epoch: 14, Loss: 0.21604090929031372
Epoch: 15, Loss: 0.20965486764907837
Epoch: 16, Loss: 0.20387177169322968
Epoch: 17, Loss: 0.19860419631004333
Epoch: 18, Loss: 0.1937815546989441
Epoch: 19, Loss: 0.18934644758701324
Epoch: 20, Loss: 0.18525134027004242
Epoch: 21, Loss: 0.1814565360546112
Epoch: 22, Loss: 0.17792858183383942
Epoch: 23, Loss: 0.17463895678520203
Epoch: 24, Loss: 0.1715632975101471
Epoch: 25, Loss: 0.16868047416210175


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5646352767944336
